#!/usr/bin/env node
/**
 * Copies .env.example → .env.local and generates local webhook secrets.
 * Run: node scripts/setup-env.mjs
 */
import { randomBytes } from "crypto";
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const examplePath = join(root, ".env.example");
const localPath = join(root, ".env.local");
const envPath = join(root, ".env");

if (!existsSync(examplePath)) {
  console.error("Missing .env.example");
  process.exit(1);
}

let content = readFileSync(examplePath, "utf8");

if (!content.includes("NEXT_PUBLIC_SITE_URL=http://localhost:3000")) {
  content = `NEXT_PUBLIC_SITE_URL=http://localhost:3000\n${content}`;
}

const stripeSecret = randomBytes(24).toString("hex");
const resendSecret = randomBytes(24).toString("hex");

function setIfEmpty(key, value) {
  const re = new RegExp(`^${key}=.*$`, "m");
  if (re.test(content)) {
    const line = content.match(re)?.[0] ?? "";
    if (line === `${key}=` || line === `${key}=""`) {
      content = content.replace(re, `${key}=${value}`);
    }
  } else {
    content += `\n${key}=${value}`;
  }
}

setIfEmpty("STRIPE_WEBHOOK_SECRET", stripeSecret);
setIfEmpty("RESEND_WEBHOOK_SECRET", resendSecret);
setIfEmpty("NEXT_PUBLIC_SITE_URL", "http://localhost:3000");
setIfEmpty("AI_MODEL_DEFAULT", "gpt-4o-mini");

const header = `# Generated by scripts/setup-env.mjs — fill Supabase, Stripe, Resend, OpenAI for full features.\n\n`;
if (!content.startsWith("# Generated")) {
  content = header + content;
}

writeFileSync(localPath, content, "utf8");
copyFileSync(localPath, envPath);
console.log("Wrote .env.local and .env");
console.log("  STRIPE_WEBHOOK_SECRET and RESEND_WEBHOOK_SECRET set for local webhooks.");
console.log("  Add NEXT_PUBLIC_SUPABASE_* and SUPABASE_SERVICE_ROLE_KEY to enable /app.");
